project:
  type: website
  preview:
    port: 7777

website:
  title: "SVS: Documentation"
  favicon: "assets/SVS - Logo - Square - SMOOSHED.png"
  open-graph: true
  repo-url: https://github.com/Rhobota/svs
  repo-subdir: "docs"
  repo-actions: [edit, source, issue]
  reader-mode: false
  page-navigation: true
  back-to-top-navigation: false
  announcement:
    icon: emoji-smile   # https://icons.getbootstrap.com/
    content: "You found <strong>SVS</strong>!"
    position: below-navbar
    dismissable: false
  navbar:
    logo: "assets/SVS - Logo - Square - SMOOSHED.png"
    background: primary
    search: true
    left:
      - text: "Quickstart"
        href: quickstart.ipynb
      - about.qmd
    right:
      - icon: github
        href: https://github.com/Rhobota/svs
        target: _blank
  sidebar:
    style: "docked"
    contents: auto
  page-footer:
    center: "Copyright © 2025 (<a href=\"https://github.com/Rhobota/svs/blob/main/LICENSE.txt\">MIT License</a>)"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
